--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TaylorR47/Meet-Bard
build-by-default: true
branches:
- main
projects:
  Meet-Bard:
    path: ""
    model: virion
    type: library
...
